window_set_caption("THE GAME");
device_height = display_get_height();
device_width = display_get_width();
aspect_ratio = device_width/device_height;
desired_height = round(device_height*aspect_ratio);
desired_width = round(device_width*aspect_ratio);
camera_width = 640;
camera_height = 340;
camera_target = obj_imposter_red1; 
surface_resize(application_surface,desired_width,desired_height);
window_set_size(desired_width,desired_height);
window_center();
_fullscreen = false;